local m1 = require("ChildMod")

local ch = m1:new(7)
local ch2 =m1:new(8)
print("Instance Value = " .. ch.num)
print("Instance Value = " .. ch2.num)
ch:addOne()
-- ch2:addOne()
-- print("Instance Value = " .. ch.num)
-- print("Instance Value = " .. ch2.num)